# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Every time I update this file without changing the content, I increment this counter.
# Counter: 1

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependency:actions"
    # Add assignees
    assignees:
      - "forgingblazor/builders"

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(sdk)"
    labels:
      - "dependency:dotnet"
    assignees:
      - "forgingblazor/builders"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependency:dotnet"
    # Add assignees
    assignees:
      - "forgingblazor/builders"
    groups:
     coverlet:
       patterns:
         - "coverlet*"
     nunit:
       patterns:
         - "nunit"
         - "nunit*"
     testcontainers:
       patterns:
         - "testcontainers*"
     tunit:
       patterns:
         - "tunit"
         - "tunit*"
     verify:
       patterns:
         - "verify*"
     xunit:
       patterns:
         - "xunit"
         - "xunit*"
