- name: dependency:actions
  description: Dependency update for `GitHub Actions`
  color: ffffff
- name: dependency:dotnet
  description: Dependency updates for `.NET and NuGet`
  color: ffffff
- name: dependency:submodule
  description: Dependency update for `Git Submodules`
  color: ffffff
- name: duplicate
  description: This issue or pull request already exists
  color: FF3F0B
- name: good first issue
  description: Good for newcomers
  color: 7057ff
- name: help wanted
  description: Extra attention is needed
  color: 008672
- name: wontfix
  description: This will not be worked on
  color: 555555