# Every time I update this file without changing the content, I increment this counter.
# Counter: 2

files:
  - "!**/*"
  - ".commitlintrc"
  - "GitVersion.yml"
  - "LICENSE"
  - ".github/CODEOWNERS"
  - ".github/FUNDING.yml"
  - ".github/ISSUE_TEMPLATE/**/*"
  - ".github/PULL_REQUEST_TEMPLATE/**/*"

  # you probably want to exclude these files:
  - "!.github/workflows/update-derived-repositories.yml"
  - "!.github/workflows/update-license.yml"
  - "!.github/template-sync.yml"
