name: Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels-dotnet.yml
  workflow_dispatch:

jobs:
  build:
    name: Synchronise labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels-dotnet.yml
